server {
    listen 20225;
    server_name 14.23.146.238;
    charset utf-8;

    root /opt/fund-valuation/dist;
    index index.html;

    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml text/javascript image/svg+xml;

    location /api/watchlist {
        proxy_pass http://127.0.0.1:5000/api/watchlist;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/fund-list {
        proxy_pass http://fund.eastmoney.com/js/fundcode_search.js;
        proxy_set_header Host fund.eastmoney.com;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header User-Agent "Mozilla/5.0";
    }

    location /api/fundgz/ {
        proxy_pass http://fundgz.1234567.com.cn/;
        proxy_set_header Host fundgz.1234567.com.cn;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header User-Agent "Mozilla/5.0";
    }

    location /api/fund-holdings {
        proxy_pass https://fundf10.eastmoney.com/FundArchivesDatas.aspx;
        proxy_set_header Host fundf10.eastmoney.com;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header User-Agent "Mozilla/5.0";
    }

    location /api/fund-nav-history {
        proxy_pass https://fundf10.eastmoney.com/F10DataApi.aspx;
        proxy_set_header Host fundf10.eastmoney.com;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header User-Agent "Mozilla/5.0";
    }
}
